[package]
name = "sumer9999dev/fastpacket"
description = "https://github.com/SUMER9999dev/FastPacket"

license = "MIT"
authors = ["SUMER <Discord: sumer_real>"]

include = ["src/FastPacket"]
exclude = ["src/FastPacket/__tests__", "FastPacket.rbxlx", "test.project.json", "src/jest.config.lua", "src/run-tests.lua", "sourcemap.json"]

version = "1.0.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
